import * as vscode from 'vscode';
import { Settings } from '../../config/settings';

export function getSidebarHtml(
    webview: vscode.Webview,
    extensionUri: vscode.Uri,
    settings: Settings,
    packageTreeHtml: string
): string {
    const defaultBuildType = settings.getDefaultBuildType();
    const defaultWorkers = settings.getDefaultParallelWorkers();
    const defaultSymlink = settings.getDefaultSymlinkInstall();
    const defaultContinue = settings.getDefaultContinueOnError();

    const html = [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '    <meta charset="UTF-8">',
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0">',
        '    <title>ROS2 Build</title>',
        '    <style>',
        '        :root { --container-padding: 10px; }',
        '        body {',
        '            padding: 0; margin: 0;',
        '            font-family: var(--vscode-font-family);',
        '            font-size: var(--vscode-font-size);',
        '            color: var(--vscode-foreground);',
        '            background-color: var(--vscode-sideBar-background);',
        '        }',
        '        .section {',
        '            padding: var(--container-padding);',
        '            border-bottom: 1px solid var(--vscode-sideBarSectionHeader-border);',
        '        }',
        '        .section-header {',
        '            display: flex; justify-content: space-between; align-items: center;',
        '            margin-bottom: 8px; font-weight: bold; font-size: 11px;',
        '            text-transform: uppercase;',
        '            color: var(--vscode-sideBarSectionHeader-foreground);',
        '        }',
        '        .form-group { margin-bottom: 8px; }',
        '        label { display: block; margin-bottom: 4px; font-size: 12px; }',
        '        select, input[type="number"] {',
        '            width: 100%; padding: 4px 8px;',
        '            background: var(--vscode-input-background);',
        '            color: var(--vscode-input-foreground);',
        '            border: 1px solid var(--vscode-input-border);',
        '            border-radius: 2px; font-size: 12px;',
        '        }',
        '        select:focus, input:focus { outline: 1px solid var(--vscode-focusBorder); }',
        '        .checkbox-group { display: flex; flex-direction: column; gap: 4px; }',
        '        .checkbox-item { display: flex; align-items: center; gap: 6px; font-size: 12px; }',
        '        .checkbox-item input[type="checkbox"] { margin: 0; }',
        '        .button-group { display: flex; flex-wrap: wrap; gap: 4px; margin-top: 8px; }',
        '        button {',
        '            padding: 4px 12px;',
        '            background: var(--vscode-button-background);',
        '            color: var(--vscode-button-foreground);',
        '            border: none; border-radius: 2px; cursor: pointer;',
        '            font-size: 12px; flex: 1; min-width: 80px;',
        '        }',
        '        button:hover { background: var(--vscode-button-hoverBackground); }',
        '        button.secondary {',
        '            background: var(--vscode-button-secondaryBackground);',
        '            color: var(--vscode-button-secondaryForeground);',
        '        }',
        '        button.secondary:hover { background: var(--vscode-button-secondaryHoverBackground); }',
        '        button.small-btn { flex: 0; min-width: auto; padding: 2px 8px; font-size: 11px; }',
        '        button.danger { background: var(--vscode-errorForeground); color: white; }',
        '        button.danger:hover { opacity: 0.9; }',
        '        .package-tree { max-height: 300px; overflow-y: auto; }',
        '        .group { margin-bottom: 4px; }',
        '        .group-header {',
        '            display: flex; align-items: center; padding: 4px 0;',
        '            cursor: pointer; user-select: none;',
        '        }',
        '        .group-header:hover { background: var(--vscode-list-hoverBackground); }',
        '        .group-toggle {',
        '            width: 16px; height: 16px;',
        '            display: flex; align-items: center; justify-content: center;',
        '            margin-right: 4px; transition: transform 0.1s;',
        '        }',
        '        .group-toggle.expanded { transform: rotate(90deg); }',
        '        .group-name { flex: 1; font-size: 12px; font-weight: 500; }',
        '        .group-count { font-size: 10px; color: var(--vscode-descriptionForeground); margin-left: 4px; }',
        '        .group-select { margin-left: 4px; }',
        '        .packages { margin-left: 20px; display: none; }',
        '        .packages.expanded { display: block; }',
        '        .package-item { display: flex; align-items: center; padding: 2px 0; font-size: 12px; }',
        '        .package-item:hover { background: var(--vscode-list-hoverBackground); }',
        '        .package-item input[type="checkbox"] { margin-right: 6px; }',
        '        .package-name { flex: 1; }',
        '        .package-type {',
        '            font-size: 10px; color: var(--vscode-descriptionForeground);',
        '            padding: 1px 4px; background: var(--vscode-badge-background);',
        '            color: var(--vscode-badge-foreground); border-radius: 2px;',
        '        }',
        '        .status-bar {',
        '            padding: 8px var(--container-padding);',
        '            background: var(--vscode-statusBar-background);',
        '            color: var(--vscode-statusBar-foreground);',
        '            font-size: 11px; display: flex; align-items: center; gap: 8px;',
        '        }',
        '        .status-icon { width: 14px; height: 14px; }',
        '        .status-icon.idle { color: var(--vscode-charts-green); }',
        '        .status-icon.building { color: var(--vscode-charts-yellow); animation: spin 1s linear infinite; }',
        '        .status-icon.error { color: var(--vscode-charts-red); }',
        '        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }',
        '        .search-box {',
        '            width: 100%; padding: 4px 8px;',
        '            background: var(--vscode-input-background);',
        '            color: var(--vscode-input-foreground);',
        '            border: 1px solid var(--vscode-input-border);',
        '            border-radius: 2px; font-size: 12px; margin-bottom: 8px;',
        '        }',
        '        .mode-toggle { display: flex; gap: 4px; margin-bottom: 8px; }',
        '        .mode-btn {',
        '            flex: 1; padding: 4px 8px;',
        '            background: var(--vscode-button-secondaryBackground);',
        '            color: var(--vscode-button-secondaryForeground);',
        '            border: none; border-radius: 2px; cursor: pointer; font-size: 11px;',
        '        }',
        '        .mode-btn.active {',
        '            background: var(--vscode-button-background);',
        '            color: var(--vscode-button-foreground);',
        '        }',
        '        .error-panel {',
        '            display: none; padding: var(--container-padding);',
        '            background: var(--vscode-inputValidation-errorBackground);',
        '            border: 1px solid var(--vscode-inputValidation-errorBorder);',
        '            margin: var(--container-padding); border-radius: 2px;',
        '            font-size: 11px; max-height: 150px; overflow-y: auto;',
        '        }',
        '        .error-panel.visible { display: block; }',
        '        .error-header {',
        '            display: flex; justify-content: space-between; align-items: center;',
        '            margin-bottom: 4px;',
        '        }',
        '        .error-title { font-weight: bold; color: var(--vscode-errorForeground); }',
        '        .error-content {',
        '            white-space: pre-wrap; word-break: break-all;',
        '            font-family: var(--vscode-editor-font-family);',
        '            font-size: 11px; line-height: 1.4;',
        '        }',
        '        .error-content .error-line { color: var(--vscode-errorForeground); }',
        '        .error-content .warning-line { color: var(--vscode-charts-yellow); }',
        '        .progress-bar {',
        '            width: 100%; height: 4px;',
        '            background: var(--vscode-progressBar-background);',
        '            border-radius: 2px; margin: 4px 0;',
        '        }',
        '        .progress-fill {',
        '            height: 100%; background: var(--vscode-charts-green);',
        '            border-radius: 2px; transition: width 0.3s;',
        '        }',
        '        .system-info {',
        '            font-size: 10px; color: var(--vscode-descriptionForeground);',
        '            padding: 4px var(--container-padding);',
        '            background: var(--vscode-sideBarSectionHeader-background);',
        '        }',
        '        .system-info-row {',
        '            display: flex; justify-content: space-between; margin: 2px 0;',
        '        }',
        '        .resizable {',
        '            position: relative;',
        '            min-height: 50px;',
        '            overflow: auto;',
        '        }',
        '        .resize-handle {',
        '            position: absolute;',
        '            bottom: 0;',
        '            left: 0;',
        '            right: 0;',
        '            height: 4px;',
        '            cursor: ns-resize;',
        '            background: var(--vscode-sideBarSectionHeader-border);',
        '        }',
        '        .resize-handle:hover {',
        '            background: var(--vscode-focusBorder);',
        '        }',
        '        .copy-feedback {',
        '            position: fixed; top: 50%; left: 50%;',
        '            transform: translate(-50%, -50%);',
        '            background: var(--vscode-notifications-background);',
        '            color: var(--vscode-notifications-foreground);',
        '            padding: 8px 16px; border-radius: 4px;',
        '            font-size: 12px; z-index: 1000; display: none;',
        '            box-shadow: 0 2px 8px rgba(0,0,0,0.2);',
        '        }',
        '        .copy-feedback.visible {',
        '            display: block; animation: fadeInOut 1.5s ease-in-out;',
        '        }',
        '        @keyframes fadeInOut {',
        '            0% { opacity: 0; } 20% { opacity: 1; }',
        '            80% { opacity: 1; } 100% { opacity: 0; }',
        '        }',
        '    </style>',
        '</head>',
        '<body>',
        '    <!-- Build Mode -->',
        '    <div class="section">',
        '        <div class="section-header">Build Mode</div>',
        '        <div class="mode-toggle">',
        '            <button class="mode-btn active" id="mode-local" onclick="setMode(\'local\')">Local</button>',
        '            <button class="mode-btn" id="mode-docker" onclick="setMode(\'docker\')">Docker ARM64</button>',
        '        </div>',
        '    </div>',
        '',
        '    <!-- Build Configuration -->',
        '    <div class="section">',
        '        <div class="section-header">Configuration</div>',
        '        <div class="form-group">',
        '            <label>Build Type</label>',
        '            <select id="buildType">',
        '                <option value="Release"' + (defaultBuildType === 'Release' ? ' selected' : '') + '>Release</option>',
        '                <option value="Debug"' + (defaultBuildType === 'Debug' ? ' selected' : '') + '>Debug</option>',
        '                <option value="RelWithDebInfo"' + (defaultBuildType === 'RelWithDebInfo' ? ' selected' : '') + '>RelWithDebInfo</option>',
        '            </select>',
        '        </div>',
        '        <div class="form-group">',
        '            <label>Parallel Workers: <span id="workers-value">' + defaultWorkers + '</span></label>',
        '            <input type="range" id="workers" min="1" max="16" value="' + defaultWorkers + '"',
        '                oninput="document.getElementById(\'workers-value\').textContent = this.value">',
        '        </div>',
        '        <div class="checkbox-group">',
        '            <div class="checkbox-item">',
        '                <input type="checkbox" id="symlink"' + (defaultSymlink ? ' checked' : '') + '>',
        '                <label for="symlink">Symlink Install</label>',
        '            </div>',
        '            <div class="checkbox-item">',
        '                <input type="checkbox" id="continueOnError"' + (defaultContinue ? ' checked' : '') + '>',
        '                <label for="continueOnError">Continue on Error</label>',
        '            </div>',
        '        </div>',
        '    </div>',
        '',
        '    <!-- Package Selection -->',
        '    <div class="section">',
        '        <div class="section-header">',
        '            <span>Packages</span>',
        '            <div style="display: flex; gap: 4px;">',
        '                <button class="secondary small-btn" onclick="selectAll()">All</button>',
        '                <button class="secondary small-btn" onclick="autoSelectByGit()" title="Auto select by Git">Git</button>',
        '                <button class="secondary small-btn" onclick="clearSelection()">Clear</button>',
        '                <button class="secondary small-btn" onclick="refresh()">Refresh</button>',
        '            </div>',
        '        </div>',
        '        <input type="text" class="search-box" placeholder="Search packages..." oninput="filterPackages(this.value)">',
        '        <div class="package-tree resizable" id="package-tree">',
        packageTreeHtml,
        '            <div class="resize-handle" id="resize-handle"></div>',
        '        </div>',
        '    </div>',
        '',
        '    <!-- Actions -->',
        '    <div class="section">',
        '        <div class="button-group">',
        '            <button onclick="buildSelected()" id="btn-build">Build Selected</button>',
        '            <button class="secondary" onclick="buildCurrent()">Build Current</button>',
        '        </div>',
        '        <div class="button-group">',
        '            <button class="secondary" onclick="buildAll()">Build All</button>',
        '            <button class="secondary" onclick="buildWithDeps()">With Deps</button>',
        '        </div>',
        '        <div class="button-group">',
        '            <button class="secondary" onclick="clean()">Clean</button>',
        '            <button class="secondary" onclick="cleanRebuild()">Clean + Rebuild</button>',
        '        </div>',
        '        <div class="button-group" id="cancel-group" style="display: none;">',
        '            <button class="danger" onclick="cancelBuild()">Cancel Build</button>',
        '        </div>',
        '    </div>',
        '',
        '    <!-- Error Panel -->',
        '    <div class="error-panel" id="error-panel">',
        '        <div class="error-header">',
        '            <span class="error-title">Build Errors</span>',
        '            <button class="secondary small-btn" onclick="copyErrors()">Copy Errors</button>',
        '        </div>',
        '        <div class="error-content" id="error-content"></div>',
        '    </div>',
        '',
        '    <!-- System Info -->',
        '    <div class="system-info" id="system-info">',
        '        <div class="system-info-row">',
        '            <span>CPU: <span id="cpu-usage">--</span>%</span>',
        '            <span>Workers: <span id="optimal-workers">--</span></span>',
        '        </div>',
        '        <div class="system-info-row">',
        '            <span>Mem: <span id="mem-usage">--</span>%</span>',
        '            <span id="build-progress-text"></span>',
        '        </div>',
        '        <div class="progress-bar" id="progress-bar" style="display: none;">',
        '            <div class="progress-fill" id="progress-fill" style="width: 0%"></div>',
        '        </div>',
        '    </div>',
        '',
        '    <!-- Status -->',
        '    <div class="status-bar" id="status-bar">',
        '        <svg class="status-icon idle" viewBox="0 0 16 16" fill="currentColor">',
        '            <path d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zm0 12.5a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11z"/>',
        '        </svg>',
        '        <span id="status-text">Ready</span>',
        '    </div>',
        '',
        '    <!-- Copy Feedback -->',
        '    <div class="copy-feedback" id="copy-feedback">Copied to clipboard</div>',
        '',
        '    <script>',
        '        var vscode = acquireVsCodeApi();',
        '        var currentMode = "local";',
        '        var lastErrors = "";',
        '',
        '        function setMode(mode) {',
        '            currentMode = mode;',
        '            document.getElementById("mode-local").classList.toggle("active", mode === "local");',
        '            document.getElementById("mode-docker").classList.toggle("active", mode === "docker");',
        '        }',
        '',
        '        function toggleGroup(groupName) {',
        '            var packages = document.getElementById("packages-" + groupName);',
        '            var toggle = document.getElementById("toggle-" + groupName);',
        '            if (packages) {',
        '                packages.classList.toggle("expanded");',
        '                if (toggle) toggle.classList.toggle("expanded");',
        '            }',
        '        }',
        '',
        '        function selectGroup(groupName, selected) {',
        '            var checkboxes = document.querySelectorAll("#packages-" + groupName + " input[type=checkbox]");',
        '            checkboxes.forEach(function(cb) {',
        '                cb.checked = selected;',
        '                vscode.postMessage({ type: "selectPackage", packageName: cb.dataset.package, selected: selected });',
        '            });',
        '        }',
        '',
        '        function togglePackage(packageName, selected) {',
        '            vscode.postMessage({ type: "selectPackage", packageName: packageName, selected: selected });',
        '        }',
        '',
        '        function buildSelected() {',
        '            document.getElementById("error-panel").classList.remove("visible");',
        '            vscode.postMessage({',
        '                type: "buildSelected",',
        '                buildType: document.getElementById("buildType").value,',
        '                workers: document.getElementById("workers").value,',
        '                symlinkInstall: document.getElementById("symlink").checked,',
        '                continueOnError: document.getElementById("continueOnError").checked,',
        '                mode: currentMode',
        '            });',
        '        }',
        '',
        '        function buildCurrent() {',
        '            document.getElementById("error-panel").classList.remove("visible");',
        '            vscode.postMessage({ type: "buildCurrent" });',
        '        }',
        '',
        '        function buildAll() {',
        '            document.getElementById("error-panel").classList.remove("visible");',
        '            vscode.postMessage({ type: "buildAll" });',
        '        }',
        '',
        '        function buildWithDeps() {',
        '            document.getElementById("error-panel").classList.remove("visible");',
        '            vscode.postMessage({ type: "buildWithDeps" });',
        '        }',
        '',
        '        function clean() {',
        '            vscode.postMessage({ type: "clean" });',
        '        }',
        '',
        '        function cleanRebuild() {',
        '            document.getElementById("error-panel").classList.remove("visible");',
        '            vscode.postMessage({ type: "cleanRebuild" });',
        '        }',
        '',
        '        function refresh() {',
        '            vscode.postMessage({ type: "refresh" });',
        '        }',
        '',
        '        function cancelBuild() {',
        '            vscode.postMessage({ type: "cancelBuild" });',
        '        }',
        '',
        '        function autoSelectByGit() {',
        '            vscode.postMessage({ type: "autoSelectByGit" });',
        '        }',
        '',
        '        function clearSelection() {',
        '            vscode.postMessage({ type: "clearSelection" });',
        '        }',
        '',
        '        function selectAll() {',
        '            vscode.postMessage({ type: "selectAll" });',
        '        }',
        '',
        '        function copyErrors() {',
        '            if (lastErrors) {',
        '                navigator.clipboard.writeText(lastErrors).then(function() {',
        '                    showCopyFeedback();',
        '                }).catch(function() {',
        '                    var textArea = document.createElement("textarea");',
        '                    textArea.value = lastErrors;',
        '                    document.body.appendChild(textArea);',
        '                    textArea.select();',
        '                    document.execCommand("copy");',
        '                    document.body.removeChild(textArea);',
        '                    showCopyFeedback();',
        '                });',
        '            }',
        '        }',
        '',
        '        function showCopyFeedback() {',
        '            var feedback = document.getElementById("copy-feedback");',
        '            feedback.classList.add("visible");',
        '            setTimeout(function() {',
        '                feedback.classList.remove("visible");',
        '            }, 1500);',
        '        }',
        '',
        '        function showError(errors) {',
        '            lastErrors = errors;',
        '            var errorPanel = document.getElementById("error-panel");',
        '            var errorContent = document.getElementById("error-content");',
        '            var lines = errors.split("\\n");',
        '            var html = "";',
        '            for (var i = 0; i < lines.length; i++) {',
        '                var line = lines[i];',
        '                if (line.indexOf("ERROR:") === 0) {',
        '                    html += \'<div class="error-line">\' + escapeHtml(line) + "</div>";',
        '                } else if (line.indexOf("WARNING:") === 0) {',
        '                    html += \'<div class="warning-line">\' + escapeHtml(line) + "</div>";',
        '                } else if (line.indexOf("===") === 0) {',
        '                    html += \'<div style="font-weight: bold; margin-top: 4px;">\' + escapeHtml(line) + "</div>";',
        '                } else {',
        '                    html += "<div>" + escapeHtml(line) + "</div>";',
        '                }',
        '            }',
        '            errorContent.innerHTML = html;',
        '            errorPanel.classList.add("visible");',
        '        }',
        '',
        '        function escapeHtml(text) {',
        '            var div = document.createElement("div");',
        '            div.textContent = text;',
        '            return div.innerHTML;',
        '        }',
        '',
        '        function formatBytes(bytes) {',
        '            if (bytes === 0) return "0 B";',
        '            var k = 1024;',
        '            var sizes = ["B", "KB", "MB", "GB", "TB"];',
        '            var i = Math.floor(Math.log(bytes) / Math.log(k));',
        '            return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + " " + sizes[i];',
        '        }',
        '',
        '        function filterPackages(query) {',
        '            var items = document.querySelectorAll(".package-item");',
        '            var groups = document.querySelectorAll(".group");',
        '            var lowerQuery = query.toLowerCase();',
        '            items.forEach(function(item) {',
        '                var name = item.querySelector(".package-name").textContent.toLowerCase();',
        '                item.style.display = name.indexOf(lowerQuery) !== -1 ? "flex" : "none";',
        '            });',
        '            groups.forEach(function(group) {',
        '                var hasVisible = false;',
        '                var pkgs = group.querySelectorAll(".package-item");',
        '                for (var i = 0; i < pkgs.length; i++) {',
        '                    if (pkgs[i].style.display !== "none") {',
        '                        hasVisible = true;',
        '                        break;',
        '                    }',
        '                }',
        '                group.style.display = hasVisible ? "block" : "none";',
        '            });',
        '        }',
        '',
        '        // Update system info',
        '        function updateSystemInfo() {',
        '            vscode.postMessage({ type: "getSystemInfo" });',
        '        }',
        '',
        '        // Periodically update system info',
        '        setInterval(updateSystemInfo, 2000);',
        '        updateSystemInfo();',
        '',
        '        // Initialize resize functionality',
        '        (function() {',
        '            var resizeHandle = document.getElementById("resize-handle");',
        '            var packageTree = document.getElementById("package-tree");',
        '            var startY, startHeight;',
        '',
        '            if (resizeHandle && packageTree) {',
        '                resizeHandle.addEventListener("mousedown", function(e) {',
        '                    startY = e.clientY;',
        '                    startHeight = packageTree.offsetHeight;',
        '                    document.addEventListener("mousemove", onMouseMove);',
        '                    document.addEventListener("mouseup", onMouseUp);',
        '                    e.preventDefault();',
        '                });',
        '',
        '                function onMouseMove(e) {',
        '                    var newHeight = startHeight + (e.clientY - startY);',
        '                    if (newHeight > 50) {',
        '                        packageTree.style.height = newHeight + "px";',
        '                        packageTree.style.maxHeight = newHeight + "px";',
        '                    }',
        '                }',
        '',
        '                function onMouseUp() {',
        '                    document.removeEventListener("mousemove", onMouseMove);',
        '                    document.removeEventListener("mouseup", onMouseUp);',
        '                }',
        '            }',
        '        })();',
        '',
        '        window.addEventListener("message", function(event) {',
        '            var message = event.data;',
        '            if (message.type === "systemInfo") {',
        '                document.getElementById("cpu-usage").textContent = message.cpuUsage;',
        '                var memText = message.memUsagePercent + "% (" + formatBytes(message.memUsed) + "/" + formatBytes(message.memTotal) + ")";',
        '                if (message.swapTotal > 0) {',
        '                    memText += " Swap:" + message.swapUsagePercent + "%";',
        '                }',
        '                document.getElementById("mem-usage").textContent = memText;',
        '                document.getElementById("optimal-workers").textContent = message.optimalWorkers;',
        '            } else if (message.type === "buildStart") {',
        '                document.getElementById("status-text").textContent = "Building...";',
        '                document.querySelector(".status-icon").className = "status-icon building";',
        '                document.getElementById("btn-build").disabled = true;',
        '                document.getElementById("cancel-group").style.display = "flex";',
        '                document.getElementById("error-panel").classList.remove("visible");',
        '                document.getElementById("progress-bar").style.display = "block";',
        '                document.getElementById("progress-fill").style.width = "0%";',
        '                document.getElementById("build-progress-text").textContent = "0/0";',
        '            } else if (message.type === "buildProgress") {',
        '                var percent = message.total > 0 ? Math.round((message.current / message.total) * 100) : 0;',
        '                document.getElementById("progress-fill").style.width = percent + "%";',
        '                document.getElementById("build-progress-text").textContent = message.current + "/" + message.total + " (" + percent + "%)";',
        '                document.getElementById("status-text").textContent = "Building: " + message.packageName + "...";',
        '            } else if (message.type === "buildComplete") {',
        '                var statusText = "";',
        '                if (message.success) {',
        '                    statusText = "Success (" + message.errors + " errors, " + message.warnings + " warnings, " + (message.duration / 1000).toFixed(1) + "s)";',
        '                } else {',
        '                    statusText = "Failed (" + message.errors + " errors, " + message.warnings + " warnings)";',
        '                }',
        '                document.getElementById("status-text").textContent = statusText;',
        '                document.querySelector(".status-icon").className = message.success ? "status-icon idle" : "status-icon error";',
        '                document.getElementById("btn-build").disabled = false;',
        '                document.getElementById("cancel-group").style.display = "none";',
        '                document.getElementById("progress-bar").style.display = "none";',
        '                if (!message.success || message.errors > 0 || message.warnings > 0) {',
        '                    showError(message.errorText || "No error details available");',
        '                }',
        '            } else if (message.type === "buildCancelled") {',
        '                document.getElementById("status-text").textContent = "Cancelled";',
        '                document.querySelector(".status-icon").className = "status-icon idle";',
        '                document.getElementById("btn-build").disabled = false;',
        '                document.getElementById("cancel-group").style.display = "none";',
        '            } else if (message.type === "refresh") {',
        '                document.getElementById("package-tree").innerHTML = message.html;',
        '            }',
        '        });',
        '    </script>',
        '</body>',
        '</html>'
    ];

    return html.join('\n');
}
